### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by radakam** [MadryLab/BREEDS-Benchmarks#2]
Hi, @ShibaniSanturkar, Dimitris Tsipras and Aleksander Madry,

I am trying to create datasets living-17 and entity-30 to use them for model training. I followed instructions exactly, but I keep getting the following error:

RuntimeError: Found 0 files in subfolders of: ./dataset/val
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif

I tried all approaches that I could find in the web, nothing works. Do you maybe know a way to fix that or what the reason might be? Is there any source where I can directly download those datasets?

Thank you in advance!

**Comment by ShibaniSanturkar** [comment]
Hi! Our code requires you to have downloaded the [ImageNet-1K](https://www.image-net.org/) dataset and have it stored under ./dataset. Have you tried doing this?

**Comment by radakam** [comment]
Exactly! I downloaded it from Kaggle, unzipped it, created dataset folder in the working directory and put train, test and val folders from ImageNet there, did not work:(

**Comment by dtsip** [comment]
Going off the error message, what are the contents of `./dataset/val`?

**Comment by radakam** [comment]
Quite some images in jpeg format
<img width="1024" alt="Screenshot 2022-11-23 at 13 13 59" src="https://user-images.githubusercontent.com/55745584/203468186-917caf0b-0d9d-45c0-a5ee-9c1ff938cbd6.png">

**Comment by dtsip** [comment]
Ah, I see.. In general, pytorch requires images to be in labeled _subfolders_, see [here](https://github.com/pytorch/examples/tree/main/imagenet) and the corresponding [extraction script](https://github.com/pytorch/examples/blob/main/imagenet/extract_ILSVRC.sh).

**Comment by radakam** [comment]
It worked, thank you!
